source/documentation/support/troubleshooting.md
I found this paragraph confusing and a bit inaccurate as we don't use the terminology 'live' anywhere else. Beta is our equivalent of a live environment right now.
If you don't think it should be removed might be possible to re-write it to something more useful?
CC @J-Lambo @ellayanor
=> remove beta paragraph

source/documentation/using_the_api/api_reference.md
Changes based on developer feedback. All examples changed to local authority eng register. URLs tidied up. 
Could someone please review this language:
"The 'local auhority eng' register". It seems unavoidable but slightly turgid.
=> Further changes to api_reference.md based on UR feedback following review 

source/documentation/getting_started/quick_start.md
After discussion with Registers developers, changes to the Quick Start guide were agreed:
Descriptions of 'base URL' and 'endpoint' have been altered and expanded. Base URL and endpoint examples now both use the 'Local authority eng' register instead of the 'Country' register. Links have been added/changed as appropriate.
=> Changes to quick_start.md based on UR feedback

source/documentation/using_the_api/api_reference.md
User research feedback suggested that when looking at the ToC, users felt the headings such as 'View a specific record' and 'View all entires' weren't technical enough and didn't make enough sense by themselves in the context of REST APIs. They felt that the information only made sense when they looked at the contents of each section. 
The changes in this commit change the subheadings (and therefore the ToC) to more technical names, to aid searching. This will be fed into the next round of UR in week 9 of Q3 to ascertain whether in this new form, this is easier for users to follow.
=> Changes to api_reference.md subheadings (and ToC)

source/documentation/using_the_api/api_reference.md
Entries endpoint seems to use `start` and `limit` instead of `page-index` and `page-size`.
=> Update API reference

source/documentation/using_the_api/api_reference.md
Move `GET /record/{field-value}/entries` from `Getting updates` section to `API Reference`
This needs review by *either* @arnau *or* @michaelabenyohai 
Thanks
=> Move `GET /record/{field-value}/entries`

source/documentation/support/troubleshooting.md
As discussed, this is a reorganisation of information pertaining to support in the API documentation. It removes information which is duplicated from the cloudapps website, and makes the support guidance more relevant to APIs 
This has been researched and we can be confident we have enough evidence (i.e. we "know" enough) to make this change now
Needs review by *either* @michaelabenyohai *or* @arnau
=> Reorg of (support) info in troubleshooting.md

source/index.html.md.erb
This is contingent on https://github.com/alphagov/registers-tech-docs/pull/17
Assuming we adopt the changes in that PR, we can remove `support_community.md` and use the content of `troubleshooting.md` (but presumably rename it, in future). 
Needs review by *either* @michaelabenyohai *or* @arnau
=> Remove support_community.md reference

source/documentation/using_the_api/api_reference.md
Moved information about `GET /register` in `Getting updates` section to first section on `GET /register` (partial duplication removed but the first section now has slightly more information)
Removed duplicated information about `GET /download-register` under original `Getting updates` section
Reorganised structure of information and headings in `Getting updates` section to start to move towards a tutorial-like format
=> Rearrangement of information in api_reference.md

source/documentation/using_the_api/rate_limits.md
It's a bit unorthodox to do this, but since it is so clear that we have no rate limits enforced, I don't see why we shouldn't just make this very simple and straightforward change. This isn't necessarily based on research but it's very minor in real terms, and is highly unlikely to impact the user journey negatively. 
This PR also removes the "contact us" element of `rate_limits.md`, which should not be necessary since there is a separate section for that.
=> Change "Rate limits" to "No rate limits"

source/documentation/getting_started/quick_start.md
* Change quick start guide
This in effect simplifies explanations of base URLs and endpoints, beyond simply extending the quick start guide
* Update links
* Delete table, apply numerous comments
Made numerous changes per conversations and removed the table, restructuring it into a list of descriptions
* Further changes to all 4 sections 
Numerous changes to all 4 sections based on feedback
* Delete redundant sentence
Sentence just repeats fact that it is a "Quick start guide"
* Change to language surrounding API inspector
Changed to reflect the fact that each register has its own inspector
* Remove redundant endpoint example
cc @nacnudus
=> Change quick start guide (#33)

source/documentation/getting_started/quick_start.md
* Change quick start guide
This in effect simplifies explanations of base URLs and endpoints, beyond simply extending the quick start guide
* Update links
* Delete table, apply numerous comments
Made numerous changes per conversations and removed the table, restructuring it into a list of descriptions
* Further changes to all 4 sections 
Numerous changes to all 4 sections based on feedback
* Delete redundant sentence
Sentence just repeats fact that it is a "Quick start guide"
* Change to language surrounding API inspector
Changed to reflect the fact that each register has its own inspector
* Remove redundant endpoint example
cc @nacnudus
=> Change quick start guide (#33) (#40)

config/tech-docs.yml, manifest.yml, nginx.conf, source/documentation/support/support.md
We now have `www.registers.service.gov.uk` && `docs.registers.service.gov.uk` so we want to use them throughout.
=> Use new service domain

manifest.yml
This route is now mapped to the docs-registers-service-redirect application which redirects to docs.registers.service.gov.uk.
=> Remove registers-docs.cloudapps.digital route

config/tech-docs.yml
- Show the crown next to GOV.UK
- Remove the "using registers" link from the navigation
=> Show crown and update nav items

Gemfile, Gemfile.lock
We want this https://github.com/alphagov/tech-docs-gem/commit/ba619c71e0b303dff767549b1e78c773aa4a3b03 so until they do a release we are pointing at master
=> Use master of govuk_tech_docs until a new release

Staticfile, manifest.yml, nginx/conf/includes/custom_header.conf
Previously we did not set any cache headers so were subject to the cloudfront default 24 hour TTL. 
This sets a `max-age` of `60` on everything. (Note I think we could introduce asset hashing and set long cache times for assets but this would be a separate task.)
=> set cache control header

source/documentation/using_the_api/api_reference.md
Some of the examples were invalid and didn't provide proper information
=> Fixed examples

manifest.yml
Bind to logit-ssl-drain (this is required for reporting)
=> bind to logit-ssl-drain

source/documentation/getting_started/quick_start.md
When I tried specifying the content types in the documentation with an `Accept` header, `text/tsv` and `text/tff` return 406 responses (406 = "not acceptable").
The supported media types are defined in the implmentation here:
https://github.com/openregister/openregister-java/blob/master/src/main/java/uk/gov/register/views/representations/ExtraMediaType.java
These are the correct values according to
- https://www.w3.org/TR/turtle/#sec-mime
- https://www.iana.org/assignments/media-types/text/tab-separated-values
=> Update content types to be consistent with the implementation

source/documentation/using_the_api/getting_updates.md
@arnau made some recommendations based on not reinforcing the use of the `limit` parameter. This is a suggested alternative to https://github.com/alphagov/registers-tech-docs/pull/105 to get around that. 
- Reorganises accordingly (simplifies and removes some content)
- Also adds some accidentally omitted content
- Uses the `government-organisation` register in the examples instead of the `country` register, since it's updated more often
- Changes example to give both `next` and `previous` in the `Link` header
=> Spinoff of 'Getting updates v3' - alternative version 

source/api_reference/get_download_register/index.html.md.erb, source/api_reference/http_status_codes/index.html.md.erb, source/api_reference/rate_limits/index.html.md.erb
The links are in the wrong order at https://docs.registers.service.gov.uk/api_reference/#api-reference
Fixes to the parameter that determines order in each of the offending files
=> Change precedence of links in API reference left-hand nav

manifest.yml
production apps should have more than one instance as per [production checklist](https://docs.cloud.service.gov.uk/deploying_apps.html#production-checklist).
run 2 instances
should deploy successfully through travis ci.
=> run 2 instances

config/tech-docs.yml
The navigation link to the registers has been changed to read 'Registers collection' on the frontend; this change does the same for the documentation navigation. (See this [card](https://trello.com/c/GDGJm4ql/3067-update-header-and-footer))
* Link text changed from 'Get data' to 'Registers collection'
None.
=> Updates link to registers collection

source/api_reference/version-history/index.html.md.erb
The change notes for the API previously said that `item-hash` was renamed to `blob-hash`. This is misleading as the actual values have changed as well.
Explain that `blob-hash` is a replacement for `item-hash`. It should only affect a minority of users who rely on partial updates (using the entry/item API).
- Check words make sense
=> Explain that blob-hash is different to item-hash

source/api_reference/version-history/index.html.md.erb
`/blobs` is implemented now (I'll deploy it tomorrow)
I've added a note about the new endpoint and how to use it.
I've also restructured this page to work better with the navigation sidebar.
The intention is that when we release this new API version, we will rename this thing from "Upgrading from v1 to next" to "Upgrading from v1 to v2", and add sections as needed when creating new versions.
At some point we will also need to create a page for `GET /blobs` but in order to do this we need a way of structuring content by version number. How we do this depends on whether we accept
https://github.com/openregister/registers-rfcs/pull/43 and just autogenerate the reference documentation. For now I'm just focusing on the "what's changed" aspect.
=> Document new /blobs endpoint

source/api_reference/version-history/index.html.md.erb
We replaced `/register` with `/context` in V2.
Explain what's changed
=> Add changenotes for the context endpoint
